"""The rollout gate promotes only confident improvements and checks itself afterwards.

The log is generated by the deployed Thompson router against known true means
(routing_offpolicy_eval.simulate_log), so "should this have been promoted" has
a right answer the gate can be held to.
"""
from __future__ import annotations

import json
import os
import sys
from dataclasses import asdict

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "scripts"))

import routing_offpolicy_eval as O  # noqa: E402
import routing_policy_gate as G  # noqa: E402

TRUTH = {"graph_first": 0.90, "hybrid": 0.85, "semantic_search": 0.55, "keyword_boosted": 0.50}


@pytest.fixture(scope="module")
def log():
    return O.simulate_log(TRUTH, n=2000, seed=3)


def test_the_best_arm_is_promoted_and_the_rest_held(log):
    assert G.gate(log, "fixed:graph_first", reps=300).decision == "PROMOTE"
    for arm in ("semantic_search", "keyword_boosted"):
        v = G.gate(log, f"fixed:{arm}", reps=300)
        assert v.decision == "HOLD" and v.lift_ci[1] < 0


def test_a_candidate_the_log_barely_covers_is_held_on_ess_alone(log):
    v = G.gate(log, "fixed:keyword_boosted", reps=300, min_lift=-1.0)
    assert v.decision == "HOLD"
    assert any("effective sample size" in r for r in v.reasons)


def test_a_lift_threshold_can_hold_a_real_but_small_improvement(log):
    v = G.gate(log, "fixed:graph_first", reps=300, min_lift=0.05)
    assert v.decision == "HOLD" and v.lift > 0


def test_greedy_logs_are_refused(log):
    greedy = [O.Record(r.question_type, r.action, 1.0, r.reward) for r in log]
    with pytest.raises(SystemExit):
        G.gate(greedy, "fixed:graph_first", reps=10)


def _verdict(lo, hi, incumbent):
    return {"candidate_ci": (lo, hi), "incumbent_value": incumbent}


def _live(values):
    return [O.Record("architecture", "graph_first", 1.0, v) for v in values]


def test_verify_distinguishes_confirmed_miscalibrated_and_inconclusive():
    confirmed = G.verify(_verdict(0.88, 0.92, 0.80), _live([0.9, 0.91, 0.89] * 100))
    assert confirmed["status"] == "CONFIRMED"
    miscal = G.verify(_verdict(0.88, 0.92, 0.80), _live([0.6, 0.62, 0.58] * 100))
    assert miscal["status"] == "MISCALIBRATED" and not miscal["predictionHeld"]
    inconclusive = G.verify(_verdict(0.80, 0.95, 0.85), _live([0.2, 1.0, 0.9, 0.4]))
    assert inconclusive["status"] == "INCONCLUSIVE"


def test_loader_prefers_the_verified_reward_and_says_which_it_used(tmp_path):
    f = tmp_path / "d.jsonl"
    f.write_text("\n".join(json.dumps(r) for r in [
        {"questionType": "general", "strategy": "hybrid", "propensity": 0.4, "confidence": 0.9, "reward": 0.2},
        {"questionType": "general", "strategy": "hybrid", "propensity": 0.4, "confidence": None, "reward": None},
    ]))
    records, source, skipped = G.load_with_reward([str(f)])
    assert [r.reward for r in records] == [0.2] and source == "verified" and skipped == 1


def test_cli_exit_codes(tmp_path, log):
    rows = [{"questionType": r.question_type, "strategy": r.action, "propensity": r.propensity,
             "reward": r.reward} for r in log]
    f = tmp_path / "d.jsonl"
    f.write_text("\n".join(json.dumps(r) for r in rows))
    out = tmp_path / "v.json"
    assert G.main(["gate", str(f), "--candidate", "fixed:graph_first", "--reps", "200", "--out", str(out)]) == 0
    assert json.loads(out.read_text())["reward_source"] == "verified"
    assert G.main(["gate", str(f), "--candidate", "fixed:semantic_search", "--reps", "200"]) == 3
